name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        # Intel mac excluded; See https://github.com/juspay/services-flake/issues/231
        system: [ x86_64-linux, aarch64-darwin ]
    steps:
      - uses: actions/checkout@v4
      - name: nixci build
        run: nixci --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" build --systems "${{ matrix.system }}"
